CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  tier INT NOT NULL DEFAULT 1,
  stars INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);
